version: '3.8'

services:
  mcp-server:
    build: .
    container_name: ecosystem-report-generator
    ports:
      - "9095:9095"
    environment:
      # Variables de entorno para la base de datos
      - DEV_SERVER=${DEV_SERVER}
      - DEV_DATABASE=${DEV_DATABASE}
      - DEV_USERNAME=${DEV_USERNAME}
      - DEV_PASSWORD=${DEV_PASSWORD}
    volumes:
      # Montar archivo .env si existe
      - ./.env:/app/.env:ro
    restart: unless-stopped
    networks:
      - mcp-network 

networks:
  mcp-network:
    driver: bridge
