[project]
name = "mpc-celuweb"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "fastmcp>=2.12.4",
    "pymssql>=1.0.0",
    "nest-asyncio>=1.5.0",
]
